apiRules:
- exclude:
    uidRegex: ^System\.Object
    type: Type
- exclude:
    uidRegex: ^UnityEngine\.Object
    type: Type
- exclude:
    uidRegex: ^UnityEngine\.Component
    type: Type
- exclude:
    uidRegex: ^UnityEngine\.Behaviour
    type: Type
- exclude:
    uidRegex: ^UnityEngine\.MonoBehaviour
    type: Type
- exclude:
    uidRegex: ^UnityEditor\.AssetPostprocessor
    type: Type
- exclude:
    uidRegex: ^UnityEditor\.EditorWindow
    type: Type
- exclude:
    uidRegex: ^UnityEngine\.ScriptableObject
    type: Type